baseURL = 'https://miscmana.com'
languageCode = 'en-us'
title = 'miscmana coming soon'
theme = 'coming-soon'

[params]
    title = "Misc Mana Coming Soon"
    description = "Contact US"
    favicon = ""
    message = "COMING SOON!"
    release = "January 1, 2025"
    background = ""

socialIcons = [
    {name = "email", url = "example@example.com"},
    {name = "twitter", url = "https://twitter.com/"},
    {name = "facebook", url = "https://facebook.com/"},
    {name = "github", url = "https://github.com/"},
    {name = "instagram", url = "https://instagram.com/"},
    {name = "tiktok", url = "https://tiktok.com/"},
    {name = "linkedin", url = "https://linkedin.com/"},
]
